name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tpl'
      - '**/*.tfpl'
      - '**/*.tmpl'
      - '**/*.tf'
      - '**/*.hcl'
      - '.github/workflows/*.yaml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
